language: cpp

sudo: false
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CONFIG=Debug
    - os: linux
      compiler: gcc
      env: CONFIG=Release
    - os: linux
      compiler: clang
      env: CONFIG=Debug
    - os: linux
      compiler: clang
      env: CONFIG=Release

install:
  - "[ $CXX = g++ ] && export CXX=g++-8 || true"

script:
  - set -e
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$CONFIG .. && make -j
  - ctest --output-on-failure
